defaults:
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  - _self_
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

experiment:
  name: Classification
  tracking_uri: sqlite:///classification.db
  logdir: ./logdir
  run_id: null

dataset:
  name: cifar100
  num_classes: 100
  root: /sda2/datasets/cifar100/ciFAIR-100
  train_file: ${dataset.root}/train.json
  test_file: ${dataset.root}/test.json

model:
  _partial_: True
  _target_: models.PreActResNet.ResNet18

data_loading:
  num_workers: 16
  num_threads: 8
  prefetch_size: 4
  progress_bar: True

training:
  lr: 0.1
  batch_size: 128
  num_epochs: 100
  momentum: 0.9
  weight_decay: 0.0005

hparams:
  resize: null
  crop_size: null
  prob_random_h_flip: 0.5
  mean: null
  std: null
  clipped_norm: null

jax:
  platform: cuda
  mem: 0.25
  disable_jit: False
  dtype: jnp.bfloat16